version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    build: ./nginx/
    ports:
      - "80:80"
  
  php:
    build: ./php/
    container_name: php
    expose:
      - 9000
    volumes:
      - ./php/:/var/www/html/